
FROM registry.access.redhat.com/ubi8/openjdk-17

ENV LANGUAGE='en_US:en'

COPY --chown=185 manager/target/*runner.jar /deployments/quarkus-run.jar

USER 185
ENV JAVA_OPTS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"